---

- name: 'Install trust-manager'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Create the trust-manager namespace'
      delegate_to: 'localhost'
      kubernetes.core.k8s:
        name: 'trust-manager'
        api_version: 'v1'
        kind: 'Namespace'
        state: 'present'

    - name: 'Install trust-manager via the helm chart'
      delegate_to: 'localhost'
      kubernetes.core.helm:
        chart_repo_url: 'https://charts.jetstack.io'
        chart_ref: 'trust-manager'
        release_name: 'trust-manager'
        release_namespace: 'trust-manager'
        release_values:
          app:
            trust:
              namespace: cert-manager

    - name: 'Wait until all pods are running'
      delegate_to: 'localhost'
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: trust-manager
      register: pod_list
      until: |
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running"]
        or
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running", "Succeeded"]
      retries: 36
      delay: 10

    - name: 'Wait until all pods are ready'
      delegate_to: 'localhost'
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: trust-manager
      register: pod_list_ready
      until: |
        pod_list_ready | json_query("resources[*].status.containerStatuses[*].ready") | unique | sort == [[true]]
      retries: 36
      delay: 10
